name: Validate Sigma rules

on:
  push:
    branches:
      - "ChangeMe!"
    paths:
      - "deprecated/**.yml"
      - "rules/**.yml"
      - "tests/test_logsource.py"
      - "tests/test_rules.py"
  pull_request:
    branches:
      - "ChangeMe!"
    paths:
      - "deprecated/**.yml"
      - "rules/**.yml"
      - "tests/test_logsource.py"
      - "tests/test_rules.py"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sigma-rules-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Sigma rules
        uses: SigmaHQ/sigma-rules-validator@v1
        with:
          paths: |-
            ./rules
          schemaFile: ${{ github.workspace }}/tests/validate-sigma-schema/sigma-schema.json
